import { VEHICLE_TYPES, VEHICLE_STATUS, BOOKING_STATUS } from './constants.js';

export const sampleVehicles = [
  // ─── BIKES ───────────────────────────────────────────
  {
    name: 'Royal Enfield Classic 350',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12AB1234',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Royal Enfield', model: 'Classic 350', year: 2024, color: 'Black', fuelType: 'petrol', transmission: 'manual', engineCapacity: '349cc', mileage: 35, topSpeed: 120 },
    pricing: { hourly: 80, daily: 800, weekly: 4500, monthly: 15000, securityDeposit: 2000, lateFeePerHour: 50 },
    location: { hub: 'Pune Central', city: 'Pune', address: 'FC Road, Shivajinagar', coordinates: { type: 'Point', coordinates: [73.8567, 18.5204] } },
    features: ['Helmet Included', 'USB Charger', 'GPS Tracker', 'Roadside Assistance'],
    description: 'Iconic cruiser perfect for city rides and highway trips. Well maintained with full service history.',
    rating: 4.8, reviewCount: 124, totalBookings: 89, isFeatured: true, gpsDeviceId: 'GPS-BIKE-001',
  },
  {
    name: 'Royal Enfield Hunter 350',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12BK2345',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Royal Enfield', model: 'Hunter 350', year: 2024, color: 'Red', fuelType: 'petrol', transmission: 'manual', engineCapacity: '349cc', mileage: 36, topSpeed: 115 },
    pricing: { hourly: 85, daily: 850, weekly: 4800, monthly: 16000, securityDeposit: 2000, lateFeePerHour: 50 },
    location: { hub: 'Pune Koregaon Park', city: 'Pune', address: 'North Main Road', coordinates: { type: 'Point', coordinates: [73.8958, 18.5362] } },
    features: ['Helmet Included', 'GPS Tracker', 'Bluetooth Console'],
    description: 'Sporty roadster with agile handling. Ideal for urban commuting and weekend getaways.',
    rating: 4.6, reviewCount: 78, totalBookings: 56, isFeatured: true, gpsDeviceId: 'GPS-BIKE-002',
  },
  {
    name: 'KTM Duke 200',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12KT3456',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'KTM', model: 'Duke 200', year: 2023, color: 'Orange', fuelType: 'petrol', transmission: 'manual', engineCapacity: '199cc', mileage: 30, topSpeed: 140 },
    pricing: { hourly: 100, daily: 950, weekly: 5200, monthly: 18000, securityDeposit: 2500, lateFeePerHour: 60 },
    location: { hub: 'Mumbai Andheri', city: 'Mumbai', address: 'Veera Desai Road', coordinates: { type: 'Point', coordinates: [72.8367, 19.1197] } },
    features: ['Helmet Included', 'GPS Tracker', 'ABS', 'Digital Console'],
    description: 'High-performance naked bike for thrill seekers. Lightweight and powerful.',
    rating: 4.9, reviewCount: 156, totalBookings: 112, isFeatured: true, gpsDeviceId: 'GPS-BIKE-003',
  },
  {
    name: 'Yamaha MT-15 V2',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12YM4567',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Yamaha', model: 'MT-15 V2', year: 2024, color: 'Dark Matte Blue', fuelType: 'petrol', transmission: 'manual', engineCapacity: '155cc', mileage: 45, topSpeed: 130 },
    pricing: { hourly: 70, daily: 650, weekly: 3800, monthly: 12000, securityDeposit: 1500, lateFeePerHour: 40 },
    location: { hub: 'Pune Hinjewadi', city: 'Pune', address: 'Phase 1, Hinjewadi IT Park', coordinates: { type: 'Point', coordinates: [73.7395, 18.5912] } },
    features: ['Helmet Included', 'GPS Tracker', 'LED Headlamps'],
    description: 'Stylish streetfighter with excellent fuel economy. Perfect for daily commute.',
    rating: 4.5, reviewCount: 92, totalBookings: 67, gpsDeviceId: 'GPS-BIKE-004',
  },
  {
    name: 'Bajaj Pulsar NS200',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12PJ5678',
    status: VEHICLE_STATUS.BOOKED,
    specs: { brand: 'Bajaj', model: 'Pulsar NS200', year: 2023, color: 'White', fuelType: 'petrol', transmission: 'manual', engineCapacity: '199cc', mileage: 40, topSpeed: 135 },
    pricing: { hourly: 75, daily: 700, weekly: 4000, monthly: 13000, securityDeposit: 1500, lateFeePerHour: 45 },
    location: { hub: 'Pune Kothrud', city: 'Pune', address: 'Karve Road', coordinates: { type: 'Point', coordinates: [73.8073, 18.5074] } },
    features: ['Helmet Included', 'GPS Tracker', 'Perimeter Frame'],
    description: 'Popular sports bike with great value. Currently on an active rental.',
    rating: 4.4, reviewCount: 203, totalBookings: 178, gpsDeviceId: 'GPS-BIKE-005',
  },
  {
    name: 'Honda CB350 H\'ness',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12HN6789',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Honda', model: 'CB350 H\'ness', year: 2024, color: 'Matte Steel Black', fuelType: 'petrol', transmission: 'manual', engineCapacity: '348cc', mileage: 38, topSpeed: 125 },
    pricing: { hourly: 90, daily: 880, weekly: 4900, monthly: 16500, securityDeposit: 2200, lateFeePerHour: 55 },
    location: { hub: 'Mumbai Bandra', city: 'Mumbai', address: 'Linking Road', coordinates: { type: 'Point', coordinates: [72.8347, 19.0596] } },
    features: ['Helmet Included', 'GPS Tracker', 'HSTC Traction Control', 'Dual Channel ABS'],
    description: 'Premium retro-modern cruiser with Honda reliability and smooth ride quality.',
    rating: 4.7, reviewCount: 65, totalBookings: 43, isFeatured: true, gpsDeviceId: 'GPS-BIKE-006',
  },
  {
    name: 'TVS Apache RTR 160 4V',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12TV7890',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'TVS', model: 'Apache RTR 160 4V', year: 2023, color: 'Racing Red', fuelType: 'petrol', transmission: 'manual', engineCapacity: '159cc', mileage: 42, topSpeed: 118 },
    pricing: { hourly: 55, daily: 500, weekly: 2800, monthly: 9500, securityDeposit: 1200, lateFeePerHour: 35 },
    location: { hub: 'Pune Wakad', city: 'Pune', address: 'Mumbai-Bangalore Highway', coordinates: { type: 'Point', coordinates: [73.7622, 18.5998] } },
    features: ['Helmet Included', 'GPS Tracker', 'Race Tuned Exhaust'],
    description: 'Track-inspired commuter with sharp handling and aggressive styling.',
    rating: 4.3, reviewCount: 145, totalBookings: 134, gpsDeviceId: 'GPS-BIKE-007',
  },
  {
    name: 'Hero XPulse 200 4V',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12XP8901',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Hero', model: 'XPulse 200 4V', year: 2024, color: 'Sports Red', fuelType: 'petrol', transmission: 'manual', engineCapacity: '199cc', mileage: 40, topSpeed: 115 },
    pricing: { hourly: 65, daily: 600, weekly: 3400, monthly: 11000, securityDeposit: 1300, lateFeePerHour: 40 },
    location: { hub: 'Pune Lonavala', city: 'Pune', address: 'Old Mumbai-Pune Highway', coordinates: { type: 'Point', coordinates: [73.4060, 18.7536] } },
    features: ['Helmet Included', 'GPS Tracker', 'Knuckle Guards', 'Long Travel Suspension'],
    description: 'Adventure tourer built for off-road trails and mountain rides to Lonavala.',
    rating: 4.6, reviewCount: 88, totalBookings: 72, isFeatured: true, gpsDeviceId: 'GPS-BIKE-008',
  },
  {
    name: 'Kawasaki Ninja 300',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12KN9012',
    status: VEHICLE_STATUS.MAINTENANCE,
    specs: { brand: 'Kawasaki', model: 'Ninja 300', year: 2022, color: 'Lime Green', fuelType: 'petrol', transmission: 'manual', engineCapacity: '296cc', mileage: 28, topSpeed: 180 },
    pricing: { hourly: 150, daily: 1400, weekly: 8000, monthly: 28000, securityDeposit: 5000, lateFeePerHour: 80 },
    location: { hub: 'Mumbai Powai', city: 'Mumbai', address: 'Hiranandani Gardens', coordinates: { type: 'Point', coordinates: [72.9051, 19.1176] } },
    features: ['Helmet Included', 'GPS Tracker', 'Dual ABS', 'Slipper Clutch'],
    description: 'Entry-level superbike. Currently under scheduled maintenance — available soon.',
    rating: 4.9, reviewCount: 47, totalBookings: 38, gpsDeviceId: 'GPS-BIKE-009',
  },
  {
    name: 'Suzuki Gixxer SF 250',
    type: VEHICLE_TYPES.BIKE,
    registrationNumber: 'MH12SZ0123',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Suzuki', model: 'Gixxer SF 250', year: 2024, color: 'Metallic Sonic Silver', fuelType: 'petrol', transmission: 'manual', engineCapacity: '249cc', mileage: 35, topSpeed: 140 },
    pricing: { hourly: 95, daily: 900, weekly: 5000, monthly: 17000, securityDeposit: 2300, lateFeePerHour: 55 },
    location: { hub: 'Pune Magarpatta', city: 'Pune', address: 'Magarpatta City', coordinates: { type: 'Point', coordinates: [73.9285, 18.5158] } },
    features: ['Helmet Included', 'GPS Tracker', 'Full Fairing', 'LED DRLs'],
    description: 'Fully faired sports commuter with refined engine and comfortable ergonomics.',
    rating: 4.5, reviewCount: 56, totalBookings: 41, gpsDeviceId: 'GPS-BIKE-010',
  },

  // ─── CARS ────────────────────────────────────────────
  {
    name: 'Hyundai Creta SX',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14CR9012',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Hyundai', model: 'Creta', year: 2024, color: 'Atlas White', fuelType: 'diesel', transmission: 'automatic', seats: 5, mileage: 18, engineCapacity: '1.5L' },
    pricing: { hourly: 300, daily: 2500, weekly: 14000, monthly: 48000, securityDeposit: 5000, lateFeePerHour: 150 },
    location: { hub: 'Pune Hinjewadi', city: 'Pune', address: 'Phase 2, Hinjewadi IT Park', coordinates: { type: 'Point', coordinates: [73.7395, 18.5912] } },
    features: ['Sunroof', 'Apple CarPlay', 'Android Auto', 'Reverse Camera', 'GPS Tracker', 'All-Weather Mats'],
    description: 'India\'s best-selling SUV. Spacious, comfortable, and perfect for family trips.',
    rating: 4.7, reviewCount: 189, totalBookings: 156, isFeatured: true, gpsDeviceId: 'GPS-CAR-001',
  },
  {
    name: 'Maruti Suzuki Swift VXI',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14SW1234',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Maruti Suzuki', model: 'Swift', year: 2023, color: 'Pearl Arctic White', fuelType: 'petrol', transmission: 'manual', seats: 5, mileage: 22, engineCapacity: '1.2L' },
    pricing: { hourly: 180, daily: 1500, weekly: 8500, monthly: 28000, securityDeposit: 3000, lateFeePerHour: 100 },
    location: { hub: 'Pune Central', city: 'Pune', address: 'Deccan Gymkhana', coordinates: { type: 'Point', coordinates: [73.8425, 18.5158] } },
    features: ['Apple CarPlay', 'Reverse Camera', 'GPS Tracker', 'Fuel Efficient'],
    description: 'Compact hatchback ideal for city driving and tight parking spaces.',
    rating: 4.4, reviewCount: 267, totalBookings: 245, gpsDeviceId: 'GPS-CAR-002',
  },
  {
    name: 'Tata Nexon XZ+',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14NX2345',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Tata', model: 'Nexon', year: 2024, color: 'Calgary White', fuelType: 'diesel', transmission: 'automatic', seats: 5, mileage: 20, engineCapacity: '1.5L' },
    pricing: { hourly: 250, daily: 2000, weekly: 11500, monthly: 38000, securityDeposit: 4000, lateFeePerHour: 120 },
    location: { hub: 'Mumbai Andheri', city: 'Mumbai', address: 'Andheri West', coordinates: { type: 'Point', coordinates: [72.8367, 19.1197] } },
    features: ['Sunroof', 'JBL Audio', '360 Camera', 'GPS Tracker', '5-Star Safety'],
    description: '5-star safety rated compact SUV with premium features and bold design.',
    rating: 4.6, reviewCount: 134, totalBookings: 98, isFeatured: true, gpsDeviceId: 'GPS-CAR-003',
  },
  {
    name: 'Honda City ZX CVT',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14HC3456',
    status: VEHICLE_STATUS.BOOKED,
    specs: { brand: 'Honda', model: 'City', year: 2024, color: 'Platinum White Pearl', fuelType: 'petrol', transmission: 'automatic', seats: 5, mileage: 17, engineCapacity: '1.5L' },
    pricing: { hourly: 280, daily: 2200, weekly: 12500, monthly: 42000, securityDeposit: 4500, lateFeePerHour: 130 },
    location: { hub: 'Pune Kothrud', city: 'Pune', address: 'Paud Road', coordinates: { type: 'Point', coordinates: [73.8073, 18.5074] } },
    features: ['Sunroof', 'Honda Sensing ADAS', 'Wireless CarPlay', 'GPS Tracker', 'Leather Seats'],
    description: 'Premium sedan with advanced driver assistance. Currently on an active rental.',
    rating: 4.8, reviewCount: 112, totalBookings: 87, gpsDeviceId: 'GPS-CAR-004',
  },
  {
    name: 'Toyota Innova Crysta GX',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14IN4567',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Toyota', model: 'Innova Crysta', year: 2023, color: 'Super White', fuelType: 'diesel', transmission: 'manual', seats: 7, mileage: 14, engineCapacity: '2.4L' },
    pricing: { hourly: 400, daily: 3500, weekly: 20000, monthly: 65000, securityDeposit: 8000, lateFeePerHour: 200 },
    location: { hub: 'Mumbai Bandra', city: 'Mumbai', address: 'Bandra Kurla Complex', coordinates: { type: 'Point', coordinates: [72.8682, 19.0728] } },
    features: ['7 Seater', 'Rear AC Vents', 'GPS Tracker', 'Roof Rails', 'Captain Seats'],
    description: 'Spacious MPV perfect for group travel, airport transfers, and outstation trips.',
    rating: 4.9, reviewCount: 178, totalBookings: 145, isFeatured: true, gpsDeviceId: 'GPS-CAR-005',
  },
  {
    name: 'Mahindra XUV700 AX7',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14XU5678',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Mahindra', model: 'XUV700', year: 2024, color: 'Midnight Black', fuelType: 'diesel', transmission: 'automatic', seats: 7, mileage: 15, engineCapacity: '2.0L' },
    pricing: { hourly: 450, daily: 3800, weekly: 22000, monthly: 72000, securityDeposit: 10000, lateFeePerHour: 220 },
    location: { hub: 'Pune Magarpatta', city: 'Pune', address: 'Magarpatta City Gate', coordinates: { type: 'Point', coordinates: [73.9285, 18.5158] } },
    features: ['Panoramic Sunroof', 'ADAS Level 2', 'Sony 3D Audio', 'GPS Tracker', '7 Airbags'],
    description: 'Feature-packed flagship SUV with Level 2 ADAS and premium cabin experience.',
    rating: 4.8, reviewCount: 95, totalBookings: 62, isFeatured: true, gpsDeviceId: 'GPS-CAR-006',
  },
  {
    name: 'Kia Seltos GTX+',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14KS6789',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Kia', model: 'Seltos', year: 2024, color: 'Gravity Grey', fuelType: 'petrol', transmission: 'automatic', seats: 5, mileage: 16, engineCapacity: '1.5L Turbo' },
    pricing: { hourly: 320, daily: 2700, weekly: 15000, monthly: 50000, securityDeposit: 5500, lateFeePerHour: 160 },
    location: { hub: 'Mumbai Powai', city: 'Mumbai', address: 'Powai Lake Road', coordinates: { type: 'Point', coordinates: [72.9051, 19.1176] } },
    features: ['Ventilated Seats', 'Bose Audio', '360 Camera', 'GPS Tracker', 'Turbo Engine'],
    description: 'Stylish connected SUV with turbo power and premium ventilated seats.',
    rating: 4.7, reviewCount: 143, totalBookings: 118, gpsDeviceId: 'GPS-CAR-007',
  },
  {
    name: 'MG Hector Sharp Pro',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14MG7890',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'MG', model: 'Hector', year: 2023, color: 'Dune Brown', fuelType: 'petrol', transmission: 'automatic', seats: 5, mileage: 14, engineCapacity: '1.5L Turbo' },
    pricing: { hourly: 350, daily: 2900, weekly: 16500, monthly: 55000, securityDeposit: 6000, lateFeePerHour: 170 },
    location: { hub: 'Pune Wakad', city: 'Pune', address: 'Wakad Main Road', coordinates: { type: 'Point', coordinates: [73.7622, 18.5998] } },
    features: ['Panoramic Sunroof', 'i-SMART Technology', '360 Camera', 'GPS Tracker', 'Ambient Lighting'],
    description: 'Connected SUV with massive touchscreen and internet car features.',
    rating: 4.5, reviewCount: 87, totalBookings: 74, gpsDeviceId: 'GPS-CAR-008',
  },
  {
    name: 'Volkswagen Virtus GT',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14VW8901',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Volkswagen', model: 'Virtus GT', year: 2024, color: 'Deep Black Pearl', fuelType: 'petrol', transmission: 'automatic', seats: 5, mileage: 15, engineCapacity: '1.5L TSI' },
    pricing: { hourly: 380, daily: 3200, weekly: 18000, monthly: 58000, securityDeposit: 7000, lateFeePerHour: 180 },
    location: { hub: 'Mumbai Bandra', city: 'Mumbai', address: 'Hill Road, Bandra West', coordinates: { type: 'Point', coordinates: [72.8347, 19.0596] } },
    features: ['Digital Cockpit', 'TSI Turbo', 'Sports Suspension', 'GPS Tracker', 'Wireless CarPlay'],
    description: 'German-engineered sedan with sporty GT trim and turbocharged performance.',
    rating: 4.6, reviewCount: 54, totalBookings: 39, gpsDeviceId: 'GPS-CAR-009',
  },
  {
    name: 'BMW 320i M Sport',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14BM9012',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'BMW', model: '320i M Sport', year: 2023, color: 'Portimao Blue', fuelType: 'petrol', transmission: 'automatic', seats: 5, mileage: 12, engineCapacity: '2.0L Turbo' },
    pricing: { hourly: 800, daily: 6500, weekly: 38000, monthly: 120000, securityDeposit: 15000, lateFeePerHour: 400 },
    location: { hub: 'Mumbai Worli', city: 'Mumbai', address: 'Atria Mall, Worli', coordinates: { type: 'Point', coordinates: [72.8156, 19.0176] } },
    features: ['M Sport Package', 'Harman Kardon', 'Live Cockpit Pro', 'GPS Tracker', 'Parking Assistant Plus'],
    description: 'Luxury sports sedan for premium experiences. M Sport styling with dynamic handling.',
    rating: 4.9, reviewCount: 32, totalBookings: 24, isFeatured: true, gpsDeviceId: 'GPS-CAR-010',
  },
  {
    name: 'Tata Punch Creative',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14TP0123',
    status: VEHICLE_STATUS.MAINTENANCE,
    specs: { brand: 'Tata', model: 'Punch', year: 2024, color: 'Tornado Blue', fuelType: 'petrol', transmission: 'manual', seats: 5, mileage: 20, engineCapacity: '1.2L' },
    pricing: { hourly: 200, daily: 1700, weekly: 9500, monthly: 32000, securityDeposit: 3500, lateFeePerHour: 110 },
    location: { hub: 'Pune Kothrud', city: 'Pune', address: 'Kothrud Depot', coordinates: { type: 'Point', coordinates: [73.8073, 18.5074] } },
    features: ['Compact SUV', '360 Camera', 'GPS Tracker', 'High Ground Clearance'],
    description: 'Micro SUV with SUV stance. Under scheduled service — back on fleet soon.',
    rating: 4.3, reviewCount: 76, totalBookings: 68, gpsDeviceId: 'GPS-CAR-011',
  },
  {
    name: 'Skoda Kushaq Style',
    type: VEHICLE_TYPES.CAR,
    registrationNumber: 'MH14SK1234',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Skoda', model: 'Kushaq', year: 2024, color: 'Candy White', fuelType: 'petrol', transmission: 'automatic', seats: 5, mileage: 17, engineCapacity: '1.0L TSI' },
    pricing: { hourly: 290, daily: 2400, weekly: 13500, monthly: 45000, securityDeposit: 4500, lateFeePerHour: 140 },
    location: { hub: 'Pune Lonavala', city: 'Pune', address: 'Lonavala Exit, Expressway', coordinates: { type: 'Point', coordinates: [73.4060, 18.7536] } },
    features: ['TSI Engine', '10" Touchscreen', 'GPS Tracker', 'Cruise Control', 'Rear AC Vents'],
    description: 'European compact SUV with solid build quality. Great for Pune-Lonavala weekend drives.',
    rating: 4.5, reviewCount: 61, totalBookings: 48, gpsDeviceId: 'GPS-CAR-012',
  },

  // ─── EVs & SCOOTERS (bonus) ──────────────────────────
  {
    name: 'Tesla Model 3 Long Range',
    type: VEHICLE_TYPES.EV,
    registrationNumber: 'MH12EV5678',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Tesla', model: 'Model 3', year: 2024, color: 'Pearl White', fuelType: 'electric', transmission: 'automatic', seats: 5, range: 500, batteryCapacity: '75 kWh' },
    pricing: { hourly: 500, daily: 4500, weekly: 25000, monthly: 85000, securityDeposit: 10000, lateFeePerHour: 250 },
    location: { hub: 'Mumbai Bandra', city: 'Mumbai', address: 'Bandra Reclamation', coordinates: { type: 'Point', coordinates: [72.8347, 19.0596] } },
    features: ['Autopilot', 'Supercharger Access', 'Premium Audio', 'GPS Tracker'],
    description: 'Premium electric sedan with autopilot and 500km range.',
    rating: 4.9, reviewCount: 41, totalBookings: 28, isFeatured: true, gpsDeviceId: 'GPS-EV-001',
  },
  {
    name: 'Ather 450X Gen 3',
    type: VEHICLE_TYPES.SCOOTER,
    registrationNumber: 'MH12SC3456',
    status: VEHICLE_STATUS.AVAILABLE,
    specs: { brand: 'Ather', model: '450X', year: 2024, color: 'Space Grey', fuelType: 'electric', range: 150, topSpeed: 90, batteryCapacity: '3.7 kWh' },
    pricing: { hourly: 50, daily: 400, weekly: 2200, monthly: 7500, securityDeposit: 1500, lateFeePerHour: 30 },
    location: { hub: 'Pune Koregaon Park', city: 'Pune', address: 'KP North Main Road', coordinates: { type: 'Point', coordinates: [73.8958, 18.5362] } },
    features: ['Fast Charging', 'Mobile App', 'GPS Tracker', 'Reverse Mode'],
    description: 'Smart electric scooter with connected features and fast charging support.',
    rating: 4.6, reviewCount: 198, totalBookings: 167, isFeatured: true, gpsDeviceId: 'GPS-SCOOT-001',
  },
];

export const sampleReviews = [
  { vehicleReg: 'MH12AB1234', rating: 5, title: 'Amazing ride!', comment: 'Classic 350 was in perfect condition. Smooth highway ride to Lonavala.' },
  { vehicleReg: 'MH12KT3456', rating: 5, title: 'Beast on wheels', comment: 'KTM Duke is thrilling. Helmet quality was excellent too.' },
  { vehicleReg: 'MH14CR9012', rating: 5, title: 'Family favourite', comment: 'Creta was spotless and spacious. Kids loved the sunroof.' },
  { vehicleReg: 'MH14IN4567', rating: 5, title: 'Best for groups', comment: 'Innova Crysta fit 7 comfortably. Driver was happy with the AC.' },
  { vehicleReg: 'MH14BM9012', rating: 5, title: 'Pure luxury', comment: 'BMW 320i was a dream to drive. Worth every rupee for special occasions.' },
  { vehicleReg: 'MH12XP8901', rating: 4, title: 'Great for trails', comment: 'XPulse handled off-road sections near Lonavala beautifully.' },
  { vehicleReg: 'MH14NX2345', rating: 4, title: 'Safe and stylish', comment: 'Nexon felt very safe with all the tech features. Clean interior.' },
  { vehicleReg: 'MH12YM4567', rating: 4, title: 'City commuter', comment: 'MT-15 is nimble in Pune traffic. Good fuel efficiency.' },
];

export const buildSampleBookings = (customerId, vehicles) => {
  const now = new Date();
  const day = 24 * 60 * 60 * 1000;

  const findVehicle = (reg) => vehicles.find((v) => v.registrationNumber === reg);

  return [
    {
      bookingNumber: 'VR-SEED-001',
      user: customerId,
      vehicle: findVehicle('MH12PJ5678')?._id,
      status: BOOKING_STATUS.ACTIVE,
      startDate: new Date(now - 1 * day),
      endDate: new Date(now + 2 * day),
      pickupLocation: { hub: 'Pune Kothrud', address: 'Karve Road, Pune' },
      pricing: { baseAmount: 2100, durationHours: 72, rateType: 'daily', rateApplied: 700, totalAmount: 2478, tax: 378, securityDeposit: 1500 },
      notes: 'Weekend ride on Pulsar NS200',
    },
    {
      bookingNumber: 'VR-SEED-002',
      user: customerId,
      vehicle: findVehicle('MH14HC3456')?._id,
      status: BOOKING_STATUS.ACTIVE,
      startDate: new Date(now - 2 * day),
      endDate: new Date(now + 1 * day),
      pickupLocation: { hub: 'Pune Kothrud', address: 'Paud Road, Pune' },
      pricing: { baseAmount: 6600, durationHours: 72, rateType: 'daily', rateApplied: 2200, totalAmount: 7788, tax: 1188, securityDeposit: 4500 },
      notes: 'Business trip in Honda City',
    },
    {
      bookingNumber: 'VR-SEED-003',
      user: customerId,
      vehicle: findVehicle('MH12AB1234')?._id,
      status: BOOKING_STATUS.COMPLETED,
      startDate: new Date(now - 14 * day),
      endDate: new Date(now - 12 * day),
      actualReturnDate: new Date(now - 12 * day),
      pickupLocation: { hub: 'Pune Central', address: 'FC Road, Pune' },
      pricing: { baseAmount: 1600, durationHours: 48, rateType: 'daily', rateApplied: 800, totalAmount: 1888, tax: 288, securityDeposit: 2000 },
    },
    {
      bookingNumber: 'VR-SEED-004',
      user: customerId,
      vehicle: findVehicle('MH14CR9012')?._id,
      status: BOOKING_STATUS.COMPLETED,
      startDate: new Date(now - 30 * day),
      endDate: new Date(now - 27 * day),
      actualReturnDate: new Date(now - 27 * day),
      pickupLocation: { hub: 'Pune Hinjewadi', address: 'Phase 2, Hinjewadi' },
      pricing: { baseAmount: 7500, durationHours: 72, rateType: 'daily', rateApplied: 2500, totalAmount: 8850, tax: 1350, securityDeposit: 5000 },
    },
    {
      bookingNumber: 'VR-SEED-005',
      user: customerId,
      vehicle: findVehicle('MH12KT3456')?._id,
      status: BOOKING_STATUS.CONFIRMED,
      startDate: new Date(now + 3 * day),
      endDate: new Date(now + 5 * day),
      pickupLocation: { hub: 'Mumbai Andheri', address: 'Veera Desai Road' },
      pricing: { baseAmount: 1900, durationHours: 48, rateType: 'daily', rateApplied: 950, totalAmount: 2242, tax: 342, securityDeposit: 2500 },
      notes: 'Upcoming Mumbai weekend on KTM Duke',
    },
    {
      bookingNumber: 'VR-SEED-006',
      user: customerId,
      vehicle: findVehicle('MH14IN4567')?._id,
      status: BOOKING_STATUS.CONFIRMED,
      startDate: new Date(now + 7 * day),
      endDate: new Date(now + 10 * day),
      pickupLocation: { hub: 'Mumbai Bandra', address: 'BKC, Mumbai' },
      pricing: { baseAmount: 10500, durationHours: 72, rateType: 'daily', rateApplied: 3500, totalAmount: 12390, tax: 1890, securityDeposit: 8000 },
      notes: 'Goa trip with Innova Crysta — 7 seater',
    },
    {
      bookingNumber: 'VR-SEED-007',
      user: customerId,
      vehicle: findVehicle('MH14SW1234')?._id,
      status: BOOKING_STATUS.CANCELLED,
      startDate: new Date(now - 5 * day),
      endDate: new Date(now - 4 * day),
      cancelledAt: new Date(now - 6 * day),
      cancellationReason: 'Plans changed',
      pickupLocation: { hub: 'Pune Central', address: 'Deccan Gymkhana' },
      pricing: { baseAmount: 1500, durationHours: 24, rateType: 'daily', rateApplied: 1500, totalAmount: 1770, tax: 270, securityDeposit: 3000 },
    },
    {
      bookingNumber: 'VR-SEED-008',
      user: customerId,
      vehicle: findVehicle('MH14BM9012')?._id,
      status: BOOKING_STATUS.COMPLETED,
      startDate: new Date(now - 20 * day),
      endDate: new Date(now - 18 * day),
      actualReturnDate: new Date(now - 18 * day),
      pickupLocation: { hub: 'Mumbai Worli', address: 'Atria Mall' },
      pricing: { baseAmount: 13000, durationHours: 48, rateType: 'daily', rateApplied: 6500, totalAmount: 15340, tax: 2340, securityDeposit: 15000 },
    },
    {
      bookingNumber: 'VR-SEED-009',
      user: customerId,
      vehicle: findVehicle('MH12XP8901')?._id,
      status: BOOKING_STATUS.COMPLETED,
      startDate: new Date(now - 10 * day),
      endDate: new Date(now - 9 * day),
      actualReturnDate: new Date(now - 9 * day),
      pickupLocation: { hub: 'Pune Lonavala', address: 'Expressway Exit' },
      pricing: { baseAmount: 600, durationHours: 24, rateType: 'daily', rateApplied: 600, totalAmount: 708, tax: 108, securityDeposit: 1300 },
    },
    {
      bookingNumber: 'VR-SEED-010',
      user: customerId,
      vehicle: findVehicle('MH14NX2345')?._id,
      status: BOOKING_STATUS.COMPLETED,
      startDate: new Date(now - 8 * day),
      endDate: new Date(now - 6 * day),
      actualReturnDate: new Date(now - 6 * day),
      pickupLocation: { hub: 'Mumbai Andheri', address: 'Andheri West' },
      pricing: { baseAmount: 4000, durationHours: 48, rateType: 'daily', rateApplied: 2000, totalAmount: 4720, tax: 720, securityDeposit: 4000 },
    },
    {
      bookingNumber: 'VR-SEED-011',
      user: customerId,
      vehicle: findVehicle('MH12YM4567')?._id,
      status: BOOKING_STATUS.COMPLETED,
      startDate: new Date(now - 15 * day),
      endDate: new Date(now - 14 * day),
      actualReturnDate: new Date(now - 14 * day),
      pickupLocation: { hub: 'Pune Hinjewadi', address: 'Phase 1' },
      pricing: { baseAmount: 650, durationHours: 24, rateType: 'daily', rateApplied: 650, totalAmount: 767, tax: 117, securityDeposit: 1500 },
    },
  ].filter((b) => b.vehicle);
};

export const buildGPSLogs = (vehicles) => {
  const logs = [];
  const bikeCarRegs = sampleVehicles
    .filter((v) => v.type === VEHICLE_TYPES.BIKE || v.type === VEHICLE_TYPES.CAR)
    .map((v) => v.registrationNumber);

  for (const reg of bikeCarRegs) {
    const vehicle = vehicles.find((v) => v.registrationNumber === reg);
    if (!vehicle?.gpsDeviceId) continue;

    const [lng, lat] = vehicle.location.coordinates.coordinates;
    const isMoving = vehicle.status === VEHICLE_STATUS.BOOKED;

    logs.push({
      vehicle: vehicle._id,
      deviceId: vehicle.gpsDeviceId,
      location: { type: 'Point', coordinates: [lng + (Math.random() - 0.5) * 0.01, lat + (Math.random() - 0.5) * 0.01] },
      speed: isMoving ? Math.floor(Math.random() * 60) + 20 : 0,
      heading: Math.floor(Math.random() * 360),
      batteryLevel: Math.floor(Math.random() * 30) + 70,
      ignition: isMoving,
      isMoving,
      odometer: Math.floor(Math.random() * 50000) + 5000,
      timestamp: new Date(),
    });
  }
  return logs;
};
